import { IFollowerDocument } from '@follower/interfaces/follower.interface';
import mongoose, { model, Model, Schema } from 'mongoose';
/*
_id: for the document will be generated by mongoose. No need to specify it, although we defined _id in our interface
{index: true}: because we'll use the followerId, followeeId to query some other colletions
ref: 'User': these ids are the one in the User collection

*/
const followerSchema: Schema = new Schema({
  followerId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
  followeeId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', index: true },
  createdAt: { type: Date, default: Date.now() }
});

const FollowerModel: Model<IFollowerDocument> = model<IFollowerDocument>('Follower', followerSchema, 'Follower');
export { FollowerModel };
